
INSERT INTO users (name, email, password, current_address, job_title, annual_income, other_household_occupants, profile_picture_url, is_landlord) VALUES ('Mini Mouse', 'example1@lhl.com', '$2a$08$PF.R9dmNCoOr8n2oBX1AS.Gts3C12Yy4jYf/lWX5hro86FmB5epai', '2595 W 1st Ave, Vancouver, BC V6K 1G8', 'Web Developer', 50000, null, 'https://64.media.tumblr.com/fbf1d966a43201c02f538d484cdfe029/tumblr_ppoakk8Gy01u1ycqw_400.jpg', true);
INSERT INTO users (name, email, password, current_address, job_title, annual_income, other_household_occupants, profile_picture_url, is_landlord) VALUES ('Felicia Okta', 'example2@lhl.com', 'password', '2597 W 1st Ave, Vancouver, BC V6K 1G8', 'Web Developer', 50000, null, 'https://images.all-free-download.com/images/graphicthumb/lady_portrait_avatar_template_cartoon_character_sketch_6849753.jpg', true);
INSERT INTO users (name, email, password, current_address, job_title, annual_income, other_household_occupants, profile_picture_url, is_landlord) VALUES ('Sumin Kim', 'example3@lhl.com', 'password', '2565 W 1st Ave, Vancouver, BC V6K 1G8', 'Web Developer', 50000, null, 'https://blog.spoongraphics.co.uk/wp-content/uploads/2017/vector-characters/13.png', true);
INSERT INTO users (name, email, password, current_address, job_title, annual_income, other_household_occupants, profile_picture_url, is_landlord) VALUES ('Andy Lindsay', 'example4@lhl.com', 'password', '2559 W 1st Ave, Vancouver, BC V6K 1G8', 'Web Developer', 100000, null, 'https://i.pinimg.com/736x/50/d4/29/50d429ea5c9afe0ef9cb3c96f784bea4.jpg', true);
INSERT INTO users (name, email, password, current_address, job_title, annual_income, other_household_occupants, profile_picture_url, is_landlord) VALUES ('Christian Nally', 'example5@lhl.com', 'password', '2549 W 1st Ave, Vancouver, BC V6K 1G8', 'Web Developer', 100000, null, 'https://speckyboy.com/wp-content/uploads/2019/05/adobe-illustrator-character-design-tutorial-16.jpg', true);
INSERT INTO users (name, email, password, current_address, job_title, annual_income, other_household_occupants, profile_picture_url, is_landlord) VALUES ('Vasiliy Klimkin', 'example6@lhl.com', 'password', '1720 Trafalgar St, Vancouver, BC V6K 3R8', 'Web Developer', 100000, null, 'https://cdn.domestika.org/c_fill,dpr_auto,f_auto,h_256,pg_1,t_base_params,w_256/v1597328748/avatars/003/889/167/3889167-original.jpg?1597328748', true);
INSERT INTO users (name, email, password, current_address, job_title, annual_income, other_household_occupants, profile_picture_url, is_landlord) VALUES ('Gary Jipp', 'example7@lhl.com', 'password', '2572 W 1st Ave, Vancouver, BC V6K 1G7', 'Web Developer', 100000, null, 'https://cdn.dribbble.com/users/408980/screenshots/3170126/man.jpg?compress=1&resize=400x300', true);
INSERT INTO users (name, email, password, current_address, job_title, annual_income, other_household_occupants, profile_picture_url, is_landlord) VALUES ('Dominic Tremblay', 'example8@lhl.com', 'password', '2560 W 1st Ave, Vancouver, BC V6K 1G7', 'Web Developer', 100000, null, 'https://media0.giphy.com/media/eLjgCiIJinQfZY9cgx/giphy.gif', true);
INSERT INTO users (name, email, password, current_address, job_title, annual_income, other_household_occupants, profile_picture_url, is_landlord) VALUES ('Francis Bourgouin', 'example9@lhl.com', 'password', '2546 W 1st Ave, Vancouver, BC V6K 1G7', 'Web Developer', 100000, null, 'https://i.ytimg.com/vi/sjk48uNBvD0/maxresdefault.jpg', true);
INSERT INTO users (name, email, password, current_address, job_title, annual_income, other_household_occupants, profile_picture_url, is_landlord) VALUES ('Egg Eggerson', 'example10@lhl.com', '$2a$08$ZL3KRQqW8VoI1MWT2Uulee/89Ab5Mm5hSc8XTs9X0rSZzasZUEUD.', '2522 W 1st Ave, Vancouver, BC V6K 1G7', 'Professional Egger', 120000, 'Startbucks Barista', 'https://www.sketchappsources.com/resources/source-image/profile-illustration-gunaldi-yunus.png', false);
INSERT INTO users (name, email, password, current_address, job_title, annual_income, other_household_occupants, profile_picture_url, is_landlord) VALUES ('Hokey Pokey', 'test@test.com', '$2a$08$ctsK4TWmMPTqgxenz0XUmeT7SRvI1U4jPVhzfcFk1AMmQSyPrr5/G', '1152 E 78st Ave, Vancouver, BC V6K 1G7', 'Dentist', 400000, 'Mcdonals', 'https://i.pinimg.com/originals/9d/f9/5d/9df95dd43337435f5713813fb1422b7f.jpg', false);




INSERT INTO properties (landlord_id, title, street, unit, city, province, postal_code, square_feet, description, property_type, number_of_bathrooms, number_of_bedrooms, listed_start_date, cost_of_month, pets_allowed) VALUES (1, 'Arbutus Nook', '3833 Arbutus St', null, 'Vancouver', 'BC', 'V6J 3Z9', 600, 'This loft-style 1 Bed 2 Bath & Den 600SF laneway house is near the intersection of Arbutus St and King Edward Ave. 10 mins drive/ 20 min bus ride to UBC and Downtown.','house', 2, 1, '2021-06-30', 2400, true);
INSERT INTO properties (landlord_id, title, street, unit, city, province, postal_code, square_feet, description, property_type, number_of_bathrooms, number_of_bedrooms, listed_start_date, cost_of_month, pets_allowed) VALUES (4, 'Little Mountain Living', '435 East 37th Avenue', null, 'Vancouver', 'BC', 'V5W 1E8', 700, 'Located on E37th bike lane, and within short walking distance to QE Park, Hillcrest Community Centre and many Main Street restaurants.', 'house', 2, 1, '2021-07-15', 1900, false);
INSERT INTO properties (landlord_id, title, street, unit, city, province, postal_code, square_feet, description, property_type, number_of_bathrooms, number_of_bedrooms, listed_start_date, cost_of_month, pets_allowed) VALUES (6, 'Oakridge Hideaway', '50 East 47th Avenue', null, 'Vancouver', 'BC', 'V5W 2A5', 650, 'Deposits: half a month security deposit. Lease term: minimum one year lease. Pets: sorry not this one. Absolutely no smoking please.', 'house', 1.5, 1, '2021-07-02', 2300, true);
INSERT INTO properties (landlord_id, title, street, unit, city, province, postal_code, square_feet, description, property_type, number_of_bathrooms, number_of_bedrooms, listed_start_date, cost_of_month, pets_allowed) VALUES (8, 'Marble Mansion', '2938 West 23rd Avenue', null, 'Vancouver', 'BC', 'V6L 1P5', 2717, 'This terrific 5 bedroom Arbutus 2 level home that has been superbly upgraded with high end stonework throughout. Almost 2 master bedrooms up make this a very unique plan. Current attached garage could be enclosed and added to living space and a garage built off of the lane if someone needed more space.', 'house', 4, 5, '2021-08-01', 5800, false);
INSERT INTO properties (landlord_id, title, street, unit, city, province, postal_code, square_feet, description, property_type, number_of_bathrooms, number_of_bedrooms, listed_start_date, cost_of_month, pets_allowed) VALUES (2, 'Primo Valentino', '625 West 53rd Avenue', 3, 'Vancouver', 'BC', 'V6P 1K2', 1100, 'About 5 minutes walk to Sir Winston Churchill secondary School. (School catchment) Only 15 minutes to Downtown, UBC; This home is designed for those looking for a family-sized home with 3 bedrooms and 2 baths has a quiet and private in the Oakridge/South Cambie area.', 'house', 2, 3, '2021-08-15', 3200, true);
INSERT INTO properties (landlord_id, title, street, unit, city, province, postal_code, square_feet, description, property_type, number_of_bathrooms, number_of_bedrooms, listed_start_date, cost_of_month, pets_allowed) VALUES (3, 'Anchor Point', '1333 Hornby St', 666, 'Vancouver', 'BC', 'V6Z 2C1', 462, 'This well designed studio suite was tastefully renoated and features hardwood flooring throughout, a modern kitchen, and spa like bathroom. The suite itself looks into the peaceful courtyard.', 'condo', 1, 1, '2021-07-01', 1900, true);
INSERT INTO properties (landlord_id, title, street, unit, city, province, postal_code, square_feet, description, property_type, number_of_bathrooms, number_of_bedrooms, listed_start_date, cost_of_month, pets_allowed) VALUES (5, 'Corner Condo', '2110 West 46th Avenue', 6, 'Vancouver', 'BC', 'V6M 2L1', 1070, 'Beautifully and tastefully renovated, fully furnished, corner unit condo with gourmet kitchen including stainless steel appliances, gas fireplace, in suite-laundry, ample storage, spacious master bedroom with ensuite, cellular blinds with top down/bottom up feature, and 2 underground parking stalls in the heart of Kerrisdale.', 'condo', 2, 2, '2021-07-01', 3100, true);
INSERT INTO properties (landlord_id, title, street, unit, city, province, postal_code, square_feet, description, property_type, number_of_bathrooms, number_of_bedrooms, listed_start_date, cost_of_month, pets_allowed) VALUES (7, 'Sparkler Parker', '5693 Elizabeth Street', null, 'Vancouver', 'BC', 'V5Y 3K1', 546, 'Welcome to The Parker by Townline. Vancouver West luxury living in the heart of the charming Oakridge hub situated between Queen Elizabeth Park and Oakridge Mall.', 'condo', 1, 1, '2021-08-01', 2050, false);
INSERT INTO properties (landlord_id, title, street, unit, city, province, postal_code, square_feet, description, property_type, number_of_bathrooms, number_of_bedrooms, listed_start_date, cost_of_month, pets_allowed) VALUES (9, 'Kingsway Family Condo', '1777 Kingsway', null, 'Vancouver', 'BC', 'V5N 2S5', 1050, 'Open concept living/dining room/kitchen, master bedroom with walk through closet and en suite, 2nd full bathroom across from the other two bedrooms (each with their own closets).', 'condo', 2, 3, '2021-08-01', 3200, false);
INSERT INTO properties (landlord_id, title, street, unit, city, province, postal_code, square_feet, description, property_type, number_of_bathrooms, number_of_bedrooms, listed_start_date, cost_of_month, pets_allowed) VALUES (2, 'Kensington Palace', '1319 36th Ave E', null, 'Vancouver', 'BC', 'V5W 1E1', 405, 'Brand new built lower suite featuring sound-proofing, and private entrance. Living area, bathroom with stand up shower, in suite washer & dryer, kitchen including Fridge and Stove, and excellent sized bedroom.', 'house', 1, 1, '2021-07-01', 1650, true);
INSERT INTO properties (landlord_id, title, street, unit, city, province, postal_code, square_feet, description, property_type, number_of_bathrooms, number_of_bedrooms, listed_start_date, cost_of_month, pets_allowed) VALUES (4, 'The Victoria Apartments', '3655 Victoria Dr', 402, 'Vancouver', 'BC', 'V5N 5K9', 550, 'Located just steps from,  most popular parks, Trout Lake, the amenities of Commercial Drive, and plenty of transit options by bike, SkyTrain or bus, The Victoria offers prime access to the best the city has to offer.', 'apartment', 1, 1, '2021-07-12', 1730, false);
INSERT INTO properties (landlord_id, title, street, unit, city, province, postal_code, square_feet, description, property_type, number_of_bathrooms, number_of_bedrooms, listed_start_date, cost_of_month, pets_allowed) VALUES (4, 'Wales Street Apartments', '5415 Wales St', null, 'Vancouver', 'BC', 'V5R 3M9', 3088, 'Spacious 5 bedroom, 1.5 bath house in Collingwood Renfrew across from Norquay Park.', 'house', 1.5, 5, '2021-01-25', 3450, true);
INSERT INTO properties (landlord_id, title, street, unit, city, province, postal_code, square_feet, description, property_type, number_of_bathrooms, number_of_bedrooms, listed_start_date, cost_of_month, pets_allowed) VALUES (2, 'The Evan Apartments', '1908 Scotia St', 330, 'Vancouver', 'BC', 'V5T 0E8', 440, 'The central location of the Evan puts you in walking proximity to all of your major destinations, including the Seawall, Terminal Skytrain Station, Chinatown, Science World, False Creek, dog parks, restaurants in every direction, emerging craft breweries and Downtown Vancouver.', 'apartment', 0, 1, '2021-03-18', 1850, true);
INSERT INTO properties (landlord_id, title, street, unit, city, province, postal_code, square_feet, description, property_type, number_of_bathrooms, number_of_bedrooms, listed_start_date, cost_of_month, pets_allowed) VALUES (8, 'Pullman Porter', '1688 Pullman Porter St', 1102, 'Vancouver', 'BC', 'V6A 0H3', 948, 'Navio at The Creek - This is Phase 2 of The Creek by Concert master planned False Creek waterfront condo community. Overlooking a 2.7 acre park on False Creek celebrated Seawall.', 'condo', 2, 2, '2020-12-15', 4200, false);
INSERT INTO properties (landlord_id, title, street, unit, city, province, postal_code, square_feet, description, property_type, number_of_bathrooms, number_of_bedrooms, listed_start_date, cost_of_month, pets_allowed) VALUES (8, 'Quebec Street', '1088 Quebec Street', 909, 'Vancouver', 'BC', 'V6A 4H2', 1170, 'Newly Renovated 1170 sqft home with 2 Bedroom 2 bath. Conveniently located beside Science World beside downtown and steps to the sea wall and skytrain.', 'condo', 2, 2, '2021-07-15', 3500, false);
INSERT INTO properties (landlord_id, title, street, unit, city, province, postal_code, square_feet, description, property_type, number_of_bathrooms, number_of_bedrooms, listed_start_date, cost_of_month, pets_allowed) VALUES (1, 'West 2nd Avenue', '159 West 2nd Ave', 202, 'Vancouver', 'BC', 'V5Y 1B8', 525, 'Tower Green At West is located in the heart of False Creek. Just steps to the Sea Wall and all the amazing restaurants, amenities and specialty shops in the Olympic Village.', 'condo', 1, 1, '2021-03-05', 2250, false);
INSERT INTO properties (landlord_id, title, street, unit, city, province, postal_code, square_feet, description, property_type, number_of_bathrooms, number_of_bedrooms, listed_start_date, cost_of_month, pets_allowed) VALUES (1, 'Quebec Street', '1661 Quebec Street', 1001, 'Vancouver', 'BC', 'V5T 1B4', 460, 'For rent is a gorgeous, fully furnished small 1 bedroom 1 bathroom unit in a 3-year-old upscale building. It is located in Olympic Village/ False Creek, right next to Science World and the seawall, so it is literally steps away from buses & the skytrain station.', 'condo', 1, 1, '2020-11-05', 2400, true);
INSERT INTO properties (landlord_id, title, street, unit, city, province, postal_code, square_feet, description, property_type, number_of_bathrooms, number_of_bedrooms, listed_start_date, cost_of_month, pets_allowed) VALUES (3, 'North Vancouver King Edward','288 King Edward Ave', 307, 'Vancouver', 'BC', 'V5Y 2J2', 1100, 'The Edward - Brand new boutique development by Mosaic. Spacious & filled with light, with 10-ft. ceilings & big windows. Huge wrap-around balcony. Quality finishings, with attention to details. Serene view of mountains & treetops. Close to Cambie Canada Line station, Queen Elizabeth Park, Cambie village, and Main Street. LEED Gold certified.', 'apartment', 2, 2, '2021-05-20', 3000, true);


INSERT INTO photos (property_id, photo_url) VALUES (1, 'https://images.unsplash.com/photo-1592928302636-c83cf1e1c887?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1050&q=80');
INSERT INTO photos (property_id, photo_url) VALUES (1, 'https://images.unsplash.com/photo-1595526051245-4506e0005bd0?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1050&q=80');
INSERT INTO photos (property_id, photo_url) VALUES (1, 'https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1794&q=80');
INSERT INTO photos (property_id, photo_url) VALUES (2, 'https://images.squarespace-cdn.com/content/v1/50c77e32e4b012358d467131/1469120722164-I4TGBQKJS1JPMC73R465/image-asset.jpeg?format=500w');
INSERT INTO photos (property_id, photo_url) VALUES (3, 'https://images.squarespace-cdn.com/content/v1/50c77e32e4b012358d467131/1625701859451-82MVPWIUTW5ILJZYTABJ/Lanefab-Willow-Residence-1117.jpg?format=2500w');
INSERT INTO photos (property_id, photo_url) VALUES (4, 'https://images.unsplash.com/photo-1598928387577-d49b6d399110?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1050&q=80');
INSERT INTO photos (property_id, photo_url) VALUES (5, 'https://images.unsplash.com/photo-1602028967263-17d1255ad02f?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1050&q=80');
INSERT INTO photos (property_id, photo_url) VALUES (6, 'https://images.unsplash.com/photo-1612965607446-25e1332775ae?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1050&q=80');
INSERT INTO photos (property_id, photo_url) VALUES (7, 'https://vancouveravenue.ca/wp-content/uploads/2018/03/1-1007-1775-Quebec-Street-Vancouver-Opsal-Building-Olympic-Village-False-Creek-Mount-Pleasant-1.jpg');
INSERT INTO photos (property_id, photo_url) VALUES (8, 'https://images.unsplash.com/photo-1591924141389-7875d935d3d1?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1050&q=80');
INSERT INTO photos (property_id, photo_url) VALUES (9, 'https://images.unsplash.com/photo-1603072845032-7b5bd641a82a?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1050&q=80');
INSERT INTO photos (property_id, photo_url) VALUES (10, 'https://images.unsplash.com/photo-1613082294483-fec382d8367e?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1050&q=80');
INSERT INTO photos (property_id, photo_url) VALUES (11, 'https://images.unsplash.com/photo-1611094016919-36b65678f3d6?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1050&q=80');
INSERT INTO photos (property_id, photo_url) VALUES (12, 'https://images.unsplash.com/photo-1571843439991-dd2b8e051966?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1050&q=80');
INSERT INTO photos (property_id, photo_url) VALUES (13, 'https://images.unsplash.com/photo-1609766857120-0183863c7971?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1050&q=80');
INSERT INTO photos (property_id, photo_url) VALUES (14, 'https://images.unsplash.com/photo-1609766857326-18a204c2cf31?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1050&q=80');
INSERT INTO photos (property_id, photo_url) VALUES (15, 'https://images.unsplash.com/photo-1602029012024-22ef00d7575a?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1050&q=80');
INSERT INTO photos (property_id, photo_url) VALUES (16, 'https://images.unsplash.com/photo-1609767175584-7abe16d3f1fa?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1050&q=80');
INSERT INTO photos (property_id, photo_url) VALUES (17, 'https://images.unsplash.com/photo-1602029073757-d1040b3b554e?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1050&q=80');
INSERT INTO photos (property_id, photo_url) VALUES (18, 'https://images.unsplash.com/photo-1560448075-cbc16bb4af8e?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1050&q=80');


INSERT INTO rentHistories (tenant_id, property_id, start_date, end_date, review_content, is_requested, is_declined) VALUES (10, 17, '2017-01-01', '2017-12-31', null, false, false);
INSERT INTO rentHistories (tenant_id, property_id, start_date, end_date, review_content, is_requested, is_declined) VALUES (10, 5, '2018-01-01', '2018-12-31', null, false, false);
INSERT INTO rentHistories (tenant_id, property_id, start_date, end_date, review_content, is_requested, is_declined) VALUES (10, 7, '2019-01-01', '2019-12-31', null, false, false);
INSERT INTO rentHistories (tenant_id, property_id, start_date, end_date, review_content, is_requested, is_declined) VALUES (11, 8, '2020-01-01', '2020-12-31', 'This tenant is quiet, respectful, pays rent on time, and a pleasure to deal with. He does not party and does not smoke. Takes good care of our property and left it in good condition.', true, false);
INSERT INTO rentHistories (tenant_id, property_id, start_date, end_date, review_content, is_requested, is_declined) VALUES (11, 3, '2021-01-01', '2021-05-31', 'This tenant often pays rent late and comes up with excuses to delay paying rent. Although he does not smoke, this tenant left several furnitures for us to dispose of and did not tell us that he broke the kitchen countertop.', true, false);



-- -- unused table
-- INSERT INTO refs (tenant_id, landlord_id) VALUES (10, 4);
-- INSERT INTO refs (tenant_id, landlord_id) VALUES (10, 2);
-- INSERT INTO refs (tenant_id, landlord_id) VALUES (10, 5);
-- INSERT INTO refs (tenant_id, landlord_id) VALUES (10, 7);
-- INSERT INTO refs (tenant_id, landlord_id) VALUES (10, 6);



-- actual application form part
INSERT INTO applications (renthistories_id, tenant_id, landlord_id, property_id, potential_move_in_date, is_declined) VALUES (5, 11, 7, 16, '2021-07-01', false);
INSERT INTO applications (renthistories_id, tenant_id, landlord_id, property_id, potential_move_in_date, is_declined) VALUES (5, 11, 6, 3, '2021-07-01', false);



INSERT INTO message_master (sender_id, receiver_id) VALUES (11, 1);

INSERT INTO message_details (message_master_id, sender_id, date_time, message_text) VALUES (1, 11, '2021-07-01', 'hi');
















